/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WebhookMethodSchema } from "./WebhookMethodSchema.js";
import { HttpHeaderSchema } from "../../service/types/HttpHeaderSchema.js";
import { WebhookPayloadSchema } from "./WebhookPayloadSchema.js";
import { ExampleWebhookCallSchema } from "../../examples/types/ExampleWebhookCallSchema.js";
import { WithAvailability } from "../../commons/types/WithAvailability.js";
import { WithAudiences } from "../../commons/types/WithAudiences.js";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema.js";
import { WithDisplayName } from "../../commons/types/WithDisplayName.js";

export const WebhookSchema: core.serialization.ObjectSchema<
    serializers.WebhookSchema.Raw,
    FernDefinition.WebhookSchema
> = core.serialization
    .object({
        method: WebhookMethodSchema,
        headers: core.serialization.record(core.serialization.string(), HttpHeaderSchema).optional(),
        payload: WebhookPayloadSchema,
        examples: core.serialization.list(ExampleWebhookCallSchema).optional(),
    })
    .extend(WithAvailability)
    .extend(WithAudiences)
    .extend(WithDocsSchema)
    .extend(WithDisplayName);

export declare namespace WebhookSchema {
    export interface Raw extends WithAvailability.Raw, WithAudiences.Raw, WithDocsSchema.Raw, WithDisplayName.Raw {
        method: WebhookMethodSchema.Raw;
        headers?: Record<string, HttpHeaderSchema.Raw> | null;
        payload: WebhookPayloadSchema.Raw;
        examples?: ExampleWebhookCallSchema.Raw[] | null;
    }
}
