/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const WebhookMethodSchema: core.serialization.Schema<
    serializers.WebhookMethodSchema.Raw,
    FernDefinition.WebhookMethodSchema
> = core.serialization.enum_(["POST", "GET"]);

export declare namespace WebhookMethodSchema {
    export type Raw = "POST" | "GET";
}
