/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WebhookReferencedPayloadSchema } from "./WebhookReferencedPayloadSchema.js";
import { WebhookInlinedPayloadSchema } from "./WebhookInlinedPayloadSchema.js";

export const WebhookPayloadSchema: core.serialization.Schema<
    serializers.WebhookPayloadSchema.Raw,
    FernDefinition.WebhookPayloadSchema
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    WebhookReferencedPayloadSchema,
    WebhookInlinedPayloadSchema,
]);

export declare namespace WebhookPayloadSchema {
    export type Raw = string | WebhookReferencedPayloadSchema.Raw | WebhookInlinedPayloadSchema.Raw;
}
