/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ApiDefinitionPathSchema } from "./ApiDefinitionPathSchema.js";
import { ApiDefinitionWithOverridesSchema } from "./ApiDefinitionWithOverridesSchema.js";
import { ApiDefinitionList } from "./ApiDefinitionList.js";
import { ProtobufApiDefinitionSchema } from "./ProtobufApiDefinitionSchema.js";
import { ApiDefinitionSchema } from "./ApiDefinitionSchema.js";

export const ApiConfigurationSchemaInternal: core.serialization.Schema<
    serializers.ApiConfigurationSchemaInternal.Raw,
    FernDefinition.ApiConfigurationSchemaInternal
> = core.serialization.undiscriminatedUnion([
    ApiDefinitionPathSchema,
    ApiDefinitionWithOverridesSchema,
    ApiDefinitionList,
    ProtobufApiDefinitionSchema,
]);

export declare namespace ApiConfigurationSchemaInternal {
    export type Raw =
        | ApiDefinitionPathSchema.Raw
        | ApiDefinitionWithOverridesSchema.Raw
        | ApiDefinitionList.Raw
        | ProtobufApiDefinitionSchema.Raw;
}
