/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ApiConfigurationSchemaInternal } from "./ApiConfigurationSchemaInternal.js";
import { NamespacedApiConfigurationSchema } from "./NamespacedApiConfigurationSchema.js";
import { ApiConfigurationV2Schema } from "./ApiConfigurationV2Schema.js";

export const ApiConfigurationSchema: core.serialization.Schema<
    serializers.ApiConfigurationSchema.Raw,
    FernDefinition.ApiConfigurationSchema
> = core.serialization.undiscriminatedUnion([
    ApiConfigurationSchemaInternal,
    NamespacedApiConfigurationSchema,
    ApiConfigurationV2Schema,
]);

export declare namespace ApiConfigurationSchema {
    export type Raw =
        | ApiConfigurationSchemaInternal.Raw
        | NamespacedApiConfigurationSchema.Raw
        | ApiConfigurationV2Schema.Raw;
}
