/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { SpecSchema } from "./SpecSchema.js";
import { ConjureSchema } from "./ConjureSchema.js";

export const ApiConfigurationV2SpecsSchema: core.serialization.Schema<
    serializers.ApiConfigurationV2SpecsSchema.Raw,
    FernDefinition.ApiConfigurationV2SpecsSchema
> = core.serialization.undiscriminatedUnion([core.serialization.list(SpecSchema), ConjureSchema]);

export declare namespace ApiConfigurationV2SpecsSchema {
    export type Raw = SpecSchema.Raw[] | ConjureSchema.Raw;
}
