/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ApiAuthSchema } from "../../fernDefinition/resources/auth/types/ApiAuthSchema.js";
import { ApiConfigurationV2SpecsSchema } from "./ApiConfigurationV2SpecsSchema.js";
import { WithHeadersSchema } from "../../fernDefinition/resources/file/types/WithHeadersSchema.js";
import { WithEnvironmentsSchema } from "../../fernDefinition/resources/environments/types/WithEnvironmentsSchema.js";

export const ApiConfigurationV2Schema: core.serialization.ObjectSchema<
    serializers.ApiConfigurationV2Schema.Raw,
    FernDefinition.ApiConfigurationV2Schema
> = core.serialization
    .object({
        auth: ApiAuthSchema.optional(),
        specs: ApiConfigurationV2SpecsSchema,
    })
    .extend(WithHeadersSchema)
    .extend(WithEnvironmentsSchema);

export declare namespace ApiConfigurationV2Schema {
    export interface Raw extends WithHeadersSchema.Raw, WithEnvironmentsSchema.Raw {
        auth?: ApiAuthSchema.Raw | null;
        specs: ApiConfigurationV2SpecsSchema.Raw;
    }
}
