/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ApiDefinitionSchema } from "./ApiDefinitionSchema.js";

export const ApiDefinitionList: core.serialization.Schema<
    serializers.ApiDefinitionList.Raw,
    FernDefinition.ApiDefinitionList
> = core.serialization.list(ApiDefinitionSchema);

export declare namespace ApiDefinitionList {
    export type Raw = ApiDefinitionSchema.Raw[];
}
