/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ApiDefinitionPathSchema: core.serialization.Schema<
    serializers.ApiDefinitionPathSchema.Raw,
    FernDefinition.ApiDefinitionPathSchema
> = core.serialization.string();

export declare namespace ApiDefinitionPathSchema {
    export type Raw = string;
}
