/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { AsyncApiSettingsSchema } from "./AsyncApiSettingsSchema.js";

export const AsyncApiSpecSchema: core.serialization.ObjectSchema<
    serializers.AsyncApiSpecSchema.Raw,
    FernDefinition.AsyncApiSpecSchema
> = core.serialization.object({
    asyncapi: core.serialization.string(),
    origin: core.serialization.string().optional(),
    overrides: core.serialization.string().optional(),
    namespace: core.serialization.string().optional(),
    settings: AsyncApiSettingsSchema.optional(),
});

export declare namespace AsyncApiSpecSchema {
    export interface Raw {
        asyncapi: string;
        origin?: string | null;
        overrides?: string | null;
        namespace?: string | null;
        settings?: AsyncApiSettingsSchema.Raw | null;
    }
}
