/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { MessageNamingSettingsSchema } from "./MessageNamingSettingsSchema.js";
import { BaseApiSettingsSchema } from "./BaseApiSettingsSchema.js";

export const AsyncApiSettingsSchema: core.serialization.ObjectSchema<
    serializers.AsyncApiSettingsSchema.Raw,
    FernDefinition.AsyncApiSettingsSchema
> = core.serialization
    .object({
        "message-naming": MessageNamingSettingsSchema.optional(),
    })
    .extend(BaseApiSettingsSchema);

export declare namespace AsyncApiSettingsSchema {
    export interface Raw extends BaseApiSettingsSchema.Raw {
        "message-naming"?: MessageNamingSettingsSchema.Raw | null;
    }
}
