/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const BaseApiSettingsSchema: core.serialization.ObjectSchema<
    serializers.BaseApiSettingsSchema.Raw,
    FernDefinition.BaseApiSettingsSchema
> = core.serialization.object({
    "respect-nullable-schemas": core.serialization.boolean().optional(),
    "title-as-schema-name": core.serialization.boolean().optional(),
    "optional-additional-properties": core.serialization.boolean().optional(),
    "coerce-enums-to-literals": core.serialization.boolean().optional(),
    "idiomatic-request-names": core.serialization.boolean().optional(),
});

export declare namespace BaseApiSettingsSchema {
    export interface Raw {
        "respect-nullable-schemas"?: boolean | null;
        "title-as-schema-name"?: boolean | null;
        "optional-additional-properties"?: boolean | null;
        "coerce-enums-to-literals"?: boolean | null;
        "idiomatic-request-names"?: boolean | null;
    }
}
