/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ConjureSchema: core.serialization.ObjectSchema<
    serializers.ConjureSchema.Raw,
    FernDefinition.ConjureSchema
> = core.serialization.object({
    conjure: core.serialization.string(),
});

export declare namespace ConjureSchema {
    export interface Raw {
        conjure: string;
    }
}
