/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { GeneratorsOpenApiObjectSchema } from "./GeneratorsOpenApiObjectSchema.js";

export const GeneratorsOpenApiSchema: core.serialization.Schema<
    serializers.GeneratorsOpenApiSchema.Raw,
    FernDefinition.GeneratorsOpenApiSchema
> = core.serialization.undiscriminatedUnion([GeneratorsOpenApiObjectSchema, core.serialization.string()]);

export declare namespace GeneratorsOpenApiSchema {
    export type Raw = GeneratorsOpenApiObjectSchema.Raw | string;
}
