/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { OutputMetadataAuthor } from "./OutputMetadataAuthor.js";

export const OutputMetadataSchema: core.serialization.ObjectSchema<
    serializers.OutputMetadataSchema.Raw,
    FernDefinition.OutputMetadataSchema
> = core.serialization.object({
    description: core.serialization.string().optional(),
    authors: core.serialization.list(OutputMetadataAuthor).optional(),
});

export declare namespace OutputMetadataSchema {
    export interface Raw {
        description?: string | null;
        authors?: OutputMetadataAuthor.Raw[] | null;
    }
}
