/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const OutputMetadataAuthor: core.serialization.ObjectSchema<
    serializers.OutputMetadataAuthor.Raw,
    FernDefinition.OutputMetadataAuthor
> = core.serialization.object({
    name: core.serialization.string(),
    email: core.serialization.string(),
});

export declare namespace OutputMetadataAuthor {
    export interface Raw {
        name: string;
        email: string;
    }
}
