/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ProtobufDefinitionSchema } from "./ProtobufDefinitionSchema.js";

export const ProtobufApiDefinitionSchema: core.serialization.ObjectSchema<
    serializers.ProtobufApiDefinitionSchema.Raw,
    FernDefinition.ProtobufApiDefinitionSchema
> = core.serialization.object({
    proto: ProtobufDefinitionSchema,
});

export declare namespace ProtobufApiDefinitionSchema {
    export interface Raw {
        proto: ProtobufDefinitionSchema.Raw;
    }
}
