/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ProtobufDefinitionSchema } from "./ProtobufDefinitionSchema.js";

export const ProtobufSpecSchema: core.serialization.ObjectSchema<
    serializers.ProtobufSpecSchema.Raw,
    FernDefinition.ProtobufSpecSchema
> = core.serialization.object({
    proto: ProtobufDefinitionSchema,
});

export declare namespace ProtobufSpecSchema {
    export interface Raw {
        proto: ProtobufDefinitionSchema.Raw;
    }
}
