/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ProtobufDefinitionSchema: core.serialization.ObjectSchema<
    serializers.ProtobufDefinitionSchema.Raw,
    FernDefinition.ProtobufDefinitionSchema
> = core.serialization.object({
    target: core.serialization.string(),
    root: core.serialization.string(),
    overrides: core.serialization.string().optional(),
    "local-generation": core.serialization.boolean().optional(),
});

export declare namespace ProtobufDefinitionSchema {
    export interface Raw {
        target: string;
        root: string;
        overrides?: string | null;
        "local-generation"?: boolean | null;
    }
}
