/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { OpenApiSpecSchema } from "./OpenApiSpecSchema.js";
import { AsyncApiSpecSchema } from "./AsyncApiSpecSchema.js";
import { ProtobufSpecSchema } from "./ProtobufSpecSchema.js";
import { OpenRpcSpecSchema } from "./OpenRpcSpecSchema.js";

export const SpecSchema: core.serialization.Schema<serializers.SpecSchema.Raw, FernDefinition.SpecSchema> =
    core.serialization.undiscriminatedUnion([
        OpenApiSpecSchema,
        AsyncApiSpecSchema,
        ProtobufSpecSchema,
        OpenRpcSpecSchema,
    ]);

export declare namespace SpecSchema {
    export type Raw = OpenApiSpecSchema.Raw | AsyncApiSpecSchema.Raw | ProtobufSpecSchema.Raw | OpenRpcSpecSchema.Raw;
}
