/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const WhitelabelGithubConfigurationSchema: core.serialization.ObjectSchema<
    serializers.WhitelabelGithubConfigurationSchema.Raw,
    FernDefinition.WhitelabelGithubConfigurationSchema
> = core.serialization.object({
    username: core.serialization.string(),
    email: core.serialization.string(),
    token: core.serialization.string(),
});

export declare namespace WhitelabelGithubConfigurationSchema {
    export interface Raw {
        username: string;
        email: string;
        token: string;
    }
}
