/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WhitelabelGithubConfigurationSchema } from "./WhitelabelGithubConfigurationSchema.js";

export const WhitelabelConfigurationSchema: core.serialization.ObjectSchema<
    serializers.WhitelabelConfigurationSchema.Raw,
    FernDefinition.WhitelabelConfigurationSchema
> = core.serialization.object({
    github: WhitelabelGithubConfigurationSchema.optional(),
});

export declare namespace WhitelabelConfigurationSchema {
    export interface Raw {
        github?: WhitelabelGithubConfigurationSchema.Raw | null;
    }
}
