# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ^generators/python/
exclude: ^generators/python/tests\/.*|generators/python/seed\/.*|^generators/python/poetry.lock|^generators/python/fastapi\/.*|^generators/python/pydantic\/.*|^generators/python/sdk\/.*
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
  - repo: https://github.com/python-poetry/poetry
    rev: "1.2"
    hooks:
      - id: poetry-check
      # - id: poetry-lock
      - id: poetry-export
