/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernSeedConfig from "../../../index.js";

export type FeatureImplementation = boolean | FernSeedConfig.FeatureImplementationWithDetails;
