/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const OpenApiSourceSchema: core.serialization.ObjectSchema<
    serializers.OpenApiSourceSchema.Raw,
    FernDefinition.OpenApiSourceSchema
> = core.serialization.object({
    openapi: core.serialization.string(),
});

export declare namespace OpenApiSourceSchema {
    export interface Raw {
        openapi: string;
    }
}
