/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { PropertyBasedErrorDiscrimination } from "./PropertyBasedErrorDiscrimination.js";
import { StatusCodeBasedErrorDiscrimination } from "./StatusCodeBasedErrorDiscrimination.js";

export const ErrorDiscriminationSchema: core.serialization.Schema<
    serializers.ErrorDiscriminationSchema.Raw,
    FernDefinition.ErrorDiscriminationSchema
> = core.serialization.undiscriminatedUnion([PropertyBasedErrorDiscrimination, StatusCodeBasedErrorDiscrimination]);

export declare namespace ErrorDiscriminationSchema {
    export type Raw = PropertyBasedErrorDiscrimination.Raw | StatusCodeBasedErrorDiscrimination.Raw;
}
