/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ExportDetailed: core.serialization.ObjectSchema<
    serializers.ExportDetailed.Raw,
    FernDefinition.ExportDetailed
> = core.serialization.object({
    dependency: core.serialization.string(),
    url: core.serialization.string().optional(),
});

export declare namespace ExportDetailed {
    export interface Raw {
        dependency: string;
        url?: string | null;
    }
}
