/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { Navigation } from "./Navigation.js";
import { Export } from "./Export.js";
import { DefinitionFileSchema } from "./DefinitionFileSchema.js";

export const PackageMarkerFileSchema: core.serialization.ObjectSchema<
    serializers.PackageMarkerFileSchema.Raw,
    FernDefinition.PackageMarkerFileSchema
> = core.serialization
    .object({
        navigation: Navigation.optional(),
        export: Export.optional(),
    })
    .extend(DefinitionFileSchema);

export declare namespace PackageMarkerFileSchema {
    export interface Raw extends DefinitionFileSchema.Raw {
        navigation?: Navigation.Raw | null;
        export?: Export.Raw | null;
    }
}
