/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const PropertyBasedErrorDiscrimination: core.serialization.ObjectSchema<
    serializers.PropertyBasedErrorDiscrimination.Raw,
    FernDefinition.PropertyBasedErrorDiscrimination
> = core.serialization.object({
    strategy: core.serialization.stringLiteral("property"),
    "property-name": core.serialization.string(),
});

export declare namespace PropertyBasedErrorDiscrimination {
    export interface Raw {
        strategy: "property";
        "property-name": string;
    }
}
