/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const StatusCodeBasedErrorDiscrimination: core.serialization.ObjectSchema<
    serializers.StatusCodeBasedErrorDiscrimination.Raw,
    FernDefinition.StatusCodeBasedErrorDiscrimination
> = core.serialization.object({
    strategy: core.serialization.stringLiteral("status-code"),
});

export declare namespace StatusCodeBasedErrorDiscrimination {
    export interface Raw {
        strategy: "status-code";
    }
}
