/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernDefinition from "../../../index.js";

export interface WithAuthSchema {
    auth?: FernDefinition.ApiAuthSchema;
    "auth-schemes"?: Record<string, FernDefinition.AuthSchemeDeclarationSchema>;
}
