/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { SingleBaseUrlEnvironmentSchema } from "./SingleBaseUrlEnvironmentSchema.js";
import { MultipleBaseUrlsEnvironmentSchema } from "./MultipleBaseUrlsEnvironmentSchema.js";

export const EnvironmentSchema: core.serialization.Schema<
    serializers.EnvironmentSchema.Raw,
    FernDefinition.EnvironmentSchema
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    SingleBaseUrlEnvironmentSchema,
    MultipleBaseUrlsEnvironmentSchema,
]);

export declare namespace EnvironmentSchema {
    export type Raw = string | SingleBaseUrlEnvironmentSchema.Raw | MultipleBaseUrlsEnvironmentSchema.Raw;
}
