changesetBaseRefs:
  - main
  - origin/main

nodeLinker: pnpm

npmScopes:
  fern-fern:
    npmRegistryServer: "https://npm.buildwithfern.com/"

packageExtensions:
  chalk@*:
    dependencies:
      "#supports-color": "npm:supports-color@9.2.2"
  debug@*:
    dependencies:
      supports-color: ^8.1.1
  follow-redirects@*:
    dependencies:
      debug: "*"
  postcss-scss@*:
    dependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - current
    - x64
    - ia32
    - arm64
