openapi: 3.0.1
info:
  title: idempotency-headers
  version: ''
paths:
  /payment:
    post:
      operationId: payment_create
      tags:
        - Payment
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
                format: uuid
              examples:
                Example1:
                  value: d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  example: 42
                currency:
                  $ref: '#/components/schemas/Currency'
              required:
                - amount
                - currency
            examples:
              Example1:
                value: {}
  /payment/{paymentId}:
    delete:
      operationId: payment_delete
      tags:
        - Payment
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
          examples:
            Example1:
              value: string
      responses:
        '204':
          description: ''
      security:
        - BearerAuth: []
components:
  schemas:
    Currency:
      title: Currency
      type: string
      enum:
        - USD
        - YEN
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
