/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as FernDefinition from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { EncodingSchema } from "../../encoding/types/EncodingSchema.js";
import { ValidationSchema } from "../../validation/types/ValidationSchema.js";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema.js";
import { WithAvailability } from "../../commons/types/WithAvailability.js";

export const BaseTypeReferenceSchema: core.serialization.ObjectSchema<
    serializers.fernDefinition.BaseTypeReferenceSchema.Raw,
    FernDefinition.fernDefinition.BaseTypeReferenceSchema
> = core.serialization
    .object({
        default: core.serialization.unknown().optional(),
        encoding: EncodingSchema.optional(),
        validation: ValidationSchema.optional(),
    })
    .extend(WithDocsSchema)
    .extend(WithAvailability);

export declare namespace BaseTypeReferenceSchema {
    export interface Raw extends WithDocsSchema.Raw, WithAvailability.Raw {
        default?: unknown | null;
        encoding?: EncodingSchema.Raw | null;
        validation?: ValidationSchema.Raw | null;
    }
}
