/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as FernDefinition from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { BaseTypeReferenceSchema } from "./BaseTypeReferenceSchema.js";
import { WithName } from "../../commons/types/WithName.js";
import { WithAudiences } from "../../commons/types/WithAudiences.js";

export const TypeReferenceDeclarationWithName: core.serialization.ObjectSchema<
    serializers.fernDefinition.TypeReferenceDeclarationWithName.Raw,
    FernDefinition.fernDefinition.TypeReferenceDeclarationWithName
> = core.serialization
    .object({
        type: core.serialization.string(),
    })
    .extend(BaseTypeReferenceSchema)
    .extend(WithName)
    .extend(WithAudiences);

export declare namespace TypeReferenceDeclarationWithName {
    export interface Raw extends BaseTypeReferenceSchema.Raw, WithName.Raw, WithAudiences.Raw {
        type: string;
    }
}
