/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ProductValue } from "./ProductValue.js";
import { ProductDeclarationHeaderSchema } from "./ProductDeclarationHeaderSchema.js";

export const ProductDeclarationSchema: core.serialization.ObjectSchema<
    serializers.ProductDeclarationSchema.Raw,
    FernDefinition.ProductDeclarationSchema
> = core.serialization.object({
    default: core.serialization.string().optional(),
    values: core.serialization.list(ProductValue),
    header: ProductDeclarationHeaderSchema,
});

export declare namespace ProductDeclarationSchema {
    export interface Raw {
        default?: string | null;
        values: ProductValue.Raw[];
        header: ProductDeclarationHeaderSchema.Raw;
    }
}
