/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ProductDeclarationHeaderObjectSchema } from "./ProductDeclarationHeaderObjectSchema.js";

export const ProductDeclarationHeaderSchema: core.serialization.Schema<
    serializers.ProductDeclarationHeaderSchema.Raw,
    FernDefinition.ProductDeclarationHeaderSchema
> = core.serialization.undiscriminatedUnion([core.serialization.string(), ProductDeclarationHeaderObjectSchema]);

export declare namespace ProductDeclarationHeaderSchema {
    export type Raw = string | ProductDeclarationHeaderObjectSchema.Raw;
}
