/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ExampleWebSocketMessage: core.serialization.ObjectSchema<
    serializers.ExampleWebSocketMessage.Raw,
    FernDefinition.ExampleWebSocketMessage
> = core.serialization.object({
    type: core.serialization.string(),
    body: core.serialization.unknown(),
});

export declare namespace ExampleWebSocketMessage {
    export interface Raw {
        type: string;
        body?: unknown;
    }
}
