/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ExampleTypeReferenceSchema: core.serialization.Schema<
    serializers.ExampleTypeReferenceSchema.Raw,
    FernDefinition.ExampleTypeReferenceSchema
> = core.serialization.unknown();

export declare namespace ExampleTypeReferenceSchema {
    export type Raw = unknown;
}
