/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ExampleTypeReferenceSchema } from "./ExampleTypeReferenceSchema.js";
import { WithName } from "../../commons/types/WithName.js";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema.js";

export const ExampleWebhookCallSchema: core.serialization.ObjectSchema<
    serializers.ExampleWebhookCallSchema.Raw,
    FernDefinition.ExampleWebhookCallSchema
> = core.serialization
    .object({
        id: core.serialization.string().optional(),
        payload: ExampleTypeReferenceSchema,
    })
    .extend(WithName)
    .extend(WithDocsSchema);

export declare namespace ExampleWebhookCallSchema {
    export interface Raw extends WithName.Raw, WithDocsSchema.Raw {
        id?: string | null;
        payload?: ExampleTypeReferenceSchema.Raw;
    }
}
