/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ExampleCodeSampleSchemaSdk } from "./ExampleCodeSampleSchemaSdk.js";
import { ExampleCodeSampleSchemaLanguage } from "./ExampleCodeSampleSchemaLanguage.js";

export const ExampleCodeSampleSchema: core.serialization.Schema<
    serializers.ExampleCodeSampleSchema.Raw,
    FernDefinition.ExampleCodeSampleSchema
> = core.serialization.undiscriminatedUnion([ExampleCodeSampleSchemaSdk, ExampleCodeSampleSchemaLanguage]);

export declare namespace ExampleCodeSampleSchema {
    export type Raw = ExampleCodeSampleSchemaSdk.Raw | ExampleCodeSampleSchemaLanguage.Raw;
}
