/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ExampleEndpointCallSchema } from "./ExampleEndpointCallSchema.js";

export const ExampleEndpointCallArraySchema: core.serialization.Schema<
    serializers.ExampleEndpointCallArraySchema.Raw,
    FernDefinition.ExampleEndpointCallArraySchema
> = core.serialization.list(ExampleEndpointCallSchema);

export declare namespace ExampleEndpointCallArraySchema {
    export type Raw = ExampleEndpointCallSchema.Raw[];
}
