openapi: 3.0.1
info:
  title: api
  version: ''
paths:
  /movies/create-movie:
    post:
      description: Add a movie to the database
      operationId: imdb_createMovie
      tags:
        - Imdb
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMovieRequest'
  /movies/{movie_id}:
    get:
      operationId: imdb_getMovie
      tags:
        - Imdb
      parameters:
        - name: movie_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/MovieId'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieId'
components:
  schemas:
    MovieId:
      title: MovieId
      type: string
    Movie:
      title: Movie
      type: object
      properties:
        _id:
          $ref: '#/components/schemas/MovieId'
        movie_title:
          type: string
        movie_rating:
          type: number
          format: double
          description: The rating scale is one to five stars
      required:
        - _id
        - movie_title
        - movie_rating
    CreateMovieRequest:
      title: CreateMovieRequest
      type: object
      properties:
        movie_title:
          type: string
        movie_rating:
          type: number
          format: double
      required:
        - movie_title
        - movie_rating
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
