openapi: 3.0.1
info:
  title: api
  version: ''
paths:
  /movies/create-movie:
    post:
      description: Add a movie to the database
      operationId: imdb_createMovie
      tags:
        - Imdb
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieId'
              examples:
                Example1:
                  value: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMovieRequest'
            examples:
              Example1:
                value: {}
  /movies/{movieId}:
    get:
      operationId: imdb_getMovie
      tags:
        - Imdb
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/MovieId'
          examples:
            Example1:
              value: string
            Example2:
              value: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
              examples:
                Example1:
                  value: {}
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieId'
components:
  schemas:
    MovieId:
      title: MovieId
      type: string
    Movie:
      title: Movie
      type: object
      properties:
        id:
          $ref: '#/components/schemas/MovieId'
        title:
          type: string
          example: string
        rating:
          type: number
          format: double
          description: The rating scale is one to five stars
          example: 1
      required:
        - id
        - title
        - rating
    CreateMovieRequest:
      title: CreateMovieRequest
      type: object
      properties:
        title:
          type: string
          example: string
        rating:
          type: number
          format: double
          example: 1
      required:
        - title
        - rating
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
