/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernDefinition from "../../../index.js";

export type ExampleCodeSampleSchema =
    | FernDefinition.ExampleCodeSampleSchemaSdk
    | FernDefinition.ExampleCodeSampleSchemaLanguage;
