/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as FernDefinition from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { StringValidationSchema } from "./StringValidationSchema.js";
import { NumberValidationSchema } from "./NumberValidationSchema.js";

export const ValidationSchema: core.serialization.Schema<
    serializers.fernDefinition.ValidationSchema.Raw,
    FernDefinition.fernDefinition.ValidationSchema
> = core.serialization.undiscriminatedUnion([StringValidationSchema, NumberValidationSchema]);

export declare namespace ValidationSchema {
    export type Raw = StringValidationSchema.Raw | NumberValidationSchema.Raw;
}
