/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema.js";

export const VariableDeclarationDetailed: core.serialization.ObjectSchema<
    serializers.VariableDeclarationDetailed.Raw,
    FernDefinition.VariableDeclarationDetailed
> = core.serialization
    .object({
        type: core.serialization.string(),
    })
    .extend(WithDocsSchema);

export declare namespace VariableDeclarationDetailed {
    export interface Raw extends WithDocsSchema.Raw {
        type: string;
    }
}
