/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ApiDefinitionSettingsSchema } from "../../generators/types/ApiDefinitionSettingsSchema.js";

export const GeneratorApiSettingsSchema: core.serialization.ObjectSchema<
    serializers.GeneratorApiSettingsSchema.Raw,
    FernDefinition.GeneratorApiSettingsSchema
> = core.serialization.object({
    settings: ApiDefinitionSettingsSchema.optional(),
});

export declare namespace GeneratorApiSettingsSchema {
    export interface Raw {
        settings?: ApiDefinitionSettingsSchema.Raw | null;
    }
}
