/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { NpmOutputLocationSchema } from "./NpmOutputLocationSchema.js";
import { MavenOutputLocationSchema } from "./MavenOutputLocationSchema.js";
import { PypiOutputLocationSchema } from "./PypiOutputLocationSchema.js";
import { PostmanOutputLocationSchema } from "./PostmanOutputLocationSchema.js";
import { LocalFileSystemOutputLocationSchema } from "./LocalFileSystemOutputLocationSchema.js";
import { NugetOutputLocationSchema } from "./NugetOutputLocationSchema.js";
import { RubyGemsOutputLocationSchema } from "./RubyGemsOutputLocationSchema.js";

export const GeneratorOutputSchema: core.serialization.Schema<
    serializers.GeneratorOutputSchema.Raw,
    FernDefinition.GeneratorOutputSchema
> = core.serialization
    .union("location", {
        npm: NpmOutputLocationSchema,
        maven: MavenOutputLocationSchema,
        pypi: PypiOutputLocationSchema,
        postman: PostmanOutputLocationSchema,
        "local-file-system": LocalFileSystemOutputLocationSchema,
        nuget: NugetOutputLocationSchema,
        rubygems: RubyGemsOutputLocationSchema,
    })
    .transform<FernDefinition.GeneratorOutputSchema>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace GeneratorOutputSchema {
    export type Raw =
        | GeneratorOutputSchema.Npm
        | GeneratorOutputSchema.Maven
        | GeneratorOutputSchema.Pypi
        | GeneratorOutputSchema.Postman
        | GeneratorOutputSchema.LocalFileSystem
        | GeneratorOutputSchema.Nuget
        | GeneratorOutputSchema.Rubygems;

    export interface Npm extends NpmOutputLocationSchema.Raw {
        location: "npm";
    }

    export interface Maven extends MavenOutputLocationSchema.Raw {
        location: "maven";
    }

    export interface Pypi extends PypiOutputLocationSchema.Raw {
        location: "pypi";
    }

    export interface Postman extends PostmanOutputLocationSchema.Raw {
        location: "postman";
    }

    export interface LocalFileSystem extends LocalFileSystemOutputLocationSchema.Raw {
        location: "local-file-system";
    }

    export interface Nuget extends NugetOutputLocationSchema.Raw {
        location: "nuget";
    }

    export interface Rubygems extends RubyGemsOutputLocationSchema.Raw {
        location: "rubygems";
    }
}
