/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const GithubCommitAndReleaseMode: core.serialization.Schema<
    serializers.GithubCommitAndReleaseMode.Raw,
    FernDefinition.GithubCommitAndReleaseMode
> = core.serialization.enum_(["commit", "release"]);

export declare namespace GithubCommitAndReleaseMode {
    export type Raw = "commit" | "release";
}
