/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const LocalFileSystemOutputLocationSchema: core.serialization.ObjectSchema<
    serializers.LocalFileSystemOutputLocationSchema.Raw,
    FernDefinition.LocalFileSystemOutputLocationSchema
> = core.serialization.object({
    path: core.serialization.string(),
});

export declare namespace LocalFileSystemOutputLocationSchema {
    export interface Raw {
        path: string;
    }
}
