/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const MavenOutputSignatureSchema: core.serialization.ObjectSchema<
    serializers.MavenOutputSignatureSchema.Raw,
    FernDefinition.MavenOutputSignatureSchema
> = core.serialization.object({
    keyId: core.serialization.string(),
    password: core.serialization.string(),
    secretKey: core.serialization.string(),
});

export declare namespace MavenOutputSignatureSchema {
    export interface Raw {
        keyId: string;
        password: string;
        secretKey: string;
    }
}
