/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { AvailabilityStatusSchema } from "./AvailabilityStatusSchema.js";
import { AvailabilitySchema } from "./AvailabilitySchema.js";

export const AvailabilityUnionSchema: core.serialization.Schema<
    serializers.AvailabilityUnionSchema.Raw,
    FernDefinition.AvailabilityUnionSchema
> = core.serialization.undiscriminatedUnion([AvailabilityStatusSchema, AvailabilitySchema]);

export declare namespace AvailabilityUnionSchema {
    export type Raw = AvailabilityStatusSchema.Raw | AvailabilitySchema.Raw;
}
