/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ExampleTypeSchema } from "../../examples/types/ExampleTypeSchema.js";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema.js";

export const ErrorDeclarationSchema: core.serialization.ObjectSchema<
    serializers.ErrorDeclarationSchema.Raw,
    FernDefinition.ErrorDeclarationSchema
> = core.serialization
    .object({
        "status-code": core.serialization.number(),
        type: core.serialization.string().optional(),
        examples: core.serialization.list(ExampleTypeSchema).optional(),
    })
    .extend(WithDocsSchema);

export declare namespace ErrorDeclarationSchema {
    export interface Raw extends WithDocsSchema.Raw {
        "status-code": number;
        type?: string | null;
        examples?: ExampleTypeSchema.Raw[] | null;
    }
}
