/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { AuthSchemeReferenceSchema } from "./AuthSchemeReferenceSchema.js";
import { AnyAuthSchemesSchema } from "./AnyAuthSchemesSchema.js";

export const ApiAuthSchema: core.serialization.Schema<serializers.ApiAuthSchema.Raw, FernDefinition.ApiAuthSchema> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        AuthSchemeReferenceSchema,
        AnyAuthSchemesSchema,
    ]);

export declare namespace ApiAuthSchema {
    export type Raw = string | AuthSchemeReferenceSchema.Raw | AnyAuthSchemesSchema.Raw;
}
