/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { OAuthSchemeSchema } from "./OAuthSchemeSchema.js";
import { HeaderAuthSchemeSchema } from "./HeaderAuthSchemeSchema.js";
import { BasicAuthSchemeSchema } from "./BasicAuthSchemeSchema.js";
import { BearerAuthSchemeSchema } from "./BearerAuthSchemeSchema.js";

export const AuthSchemeDeclarationSchema: core.serialization.Schema<
    serializers.AuthSchemeDeclarationSchema.Raw,
    FernDefinition.AuthSchemeDeclarationSchema
> = core.serialization.undiscriminatedUnion([
    OAuthSchemeSchema,
    HeaderAuthSchemeSchema,
    BasicAuthSchemeSchema,
    BearerAuthSchemeSchema,
]);

export declare namespace AuthSchemeDeclarationSchema {
    export type Raw =
        | OAuthSchemeSchema.Raw
        | HeaderAuthSchemeSchema.Raw
        | BasicAuthSchemeSchema.Raw
        | BearerAuthSchemeSchema.Raw;
}
