/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WithEnvironmentVariable } from "./WithEnvironmentVariable.js";
import { WithName } from "../../commons/types/WithName.js";

export const AuthVariable: core.serialization.ObjectSchema<serializers.AuthVariable.Raw, FernDefinition.AuthVariable> =
    core.serialization.object({}).extend(WithEnvironmentVariable).extend(WithName);

export declare namespace AuthVariable {
    export interface Raw extends WithEnvironmentVariable.Raw, WithName.Raw {}
}
