/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { AuthVariable } from "./AuthVariable.js";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema.js";

export const BearerAuthSchemeSchema: core.serialization.ObjectSchema<
    serializers.BearerAuthSchemeSchema.Raw,
    FernDefinition.BearerAuthSchemeSchema
> = core.serialization
    .object({
        scheme: core.serialization.stringLiteral("bearer"),
        token: AuthVariable.optional(),
    })
    .extend(WithDocsSchema);

export declare namespace BearerAuthSchemeSchema {
    export interface Raw extends WithDocsSchema.Raw {
        scheme: "bearer";
        token?: AuthVariable.Raw | null;
    }
}
