/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WithEnvironmentVariable } from "./WithEnvironmentVariable.js";
import { WithName } from "../../commons/types/WithName.js";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema.js";

export const HeaderAuthSchemeSchema: core.serialization.ObjectSchema<
    serializers.HeaderAuthSchemeSchema.Raw,
    FernDefinition.HeaderAuthSchemeSchema
> = core.serialization
    .object({
        header: core.serialization.string(),
        type: core.serialization.string().optional(),
        prefix: core.serialization.string().optional(),
    })
    .extend(WithEnvironmentVariable)
    .extend(WithName)
    .extend(WithDocsSchema);

export declare namespace HeaderAuthSchemeSchema {
    export interface Raw extends WithEnvironmentVariable.Raw, WithName.Raw, WithDocsSchema.Raw {
        header: string;
        type?: string | null;
        prefix?: string | null;
    }
}
