/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ApiAuthSchema } from "./ApiAuthSchema.js";
import { AuthSchemeDeclarationSchema } from "./AuthSchemeDeclarationSchema.js";

export const WithAuthSchema: core.serialization.ObjectSchema<
    serializers.WithAuthSchema.Raw,
    FernDefinition.WithAuthSchema
> = core.serialization.object({
    auth: ApiAuthSchema.optional(),
    "auth-schemes": core.serialization.record(core.serialization.string(), AuthSchemeDeclarationSchema).optional(),
});

export declare namespace WithAuthSchema {
    export interface Raw {
        auth?: ApiAuthSchema.Raw | null;
        "auth-schemes"?: Record<string, AuthSchemeDeclarationSchema.Raw> | null;
    }
}
