/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WebSocketOrigin } from "./WebSocketOrigin.js";
import { WebSocketChannelMessageBodySchema } from "./WebSocketChannelMessageBodySchema.js";
import { DeclarationSchema } from "../../commons/types/DeclarationSchema.js";
import { WithDisplayName } from "../../commons/types/WithDisplayName.js";

export const WebSocketChannelMessageSchema: core.serialization.ObjectSchema<
    serializers.WebSocketChannelMessageSchema.Raw,
    FernDefinition.WebSocketChannelMessageSchema
> = core.serialization
    .object({
        origin: WebSocketOrigin,
        body: WebSocketChannelMessageBodySchema,
    })
    .extend(DeclarationSchema)
    .extend(WithDisplayName);

export declare namespace WebSocketChannelMessageSchema {
    export interface Raw extends DeclarationSchema.Raw, WithDisplayName.Raw {
        origin: WebSocketOrigin.Raw;
        body: WebSocketChannelMessageBodySchema.Raw;
    }
}
