/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WebSocketChannelReferencedMessageSchema } from "./WebSocketChannelReferencedMessageSchema.js";
import { WebSocketChannelInlinedMessageSchema } from "./WebSocketChannelInlinedMessageSchema.js";

export const WebSocketChannelMessageBodySchema: core.serialization.Schema<
    serializers.WebSocketChannelMessageBodySchema.Raw,
    FernDefinition.WebSocketChannelMessageBodySchema
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    WebSocketChannelReferencedMessageSchema,
    WebSocketChannelInlinedMessageSchema,
]);

export declare namespace WebSocketChannelMessageBodySchema {
    export type Raw = string | WebSocketChannelReferencedMessageSchema.Raw | WebSocketChannelInlinedMessageSchema.Raw;
}
