/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const WebSocketOrigin: core.serialization.Schema<
    serializers.WebSocketOrigin.Raw,
    FernDefinition.WebSocketOrigin
> = core.serialization.enum_(["client", "server"]);

export declare namespace WebSocketOrigin {
    export type Raw = "client" | "server";
}
