/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernDefinition from "../../../index.js";

export interface AsyncApiSpecSchema {
    asyncapi: string;
    origin?: string;
    overrides?: string;
    namespace?: string;
    settings?: FernDefinition.AsyncApiSettingsSchema;
}
