/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernDefinition from "../../../index.js";

export interface BaseTypeReferenceSchema extends FernDefinition.WithDocsSchema, FernDefinition.WithAvailability {
    default?: unknown;
    encoding?: FernDefinition.EncodingSchema;
    validation?: FernDefinition.ValidationSchema;
}
