/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ReviewerSchema: core.serialization.ObjectSchema<
    serializers.ReviewerSchema.Raw,
    FernDefinition.ReviewerSchema
> = core.serialization.object({
    name: core.serialization.string(),
});

export declare namespace ReviewerSchema {
    export interface Raw {
        name: string;
    }
}
