/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WithDocsSchema } from "./WithDocsSchema.js";
import { WithAvailability } from "./WithAvailability.js";
import { WithAudiences } from "./WithAudiences.js";

export const DeclarationSchema: core.serialization.ObjectSchema<
    serializers.DeclarationSchema.Raw,
    FernDefinition.DeclarationSchema
> = core.serialization.object({}).extend(WithDocsSchema).extend(WithAvailability).extend(WithAudiences);

export declare namespace DeclarationSchema {
    export interface Raw extends WithDocsSchema.Raw, WithAvailability.Raw, WithAudiences.Raw {}
}
