/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { WithAvailability } from "./WithAvailability.js";
import { WithAudiences } from "./WithAudiences.js";

export const DeclarationWithoutDocsSchema: core.serialization.ObjectSchema<
    serializers.DeclarationWithoutDocsSchema.Raw,
    FernDefinition.DeclarationWithoutDocsSchema
> = core.serialization.object({}).extend(WithAvailability).extend(WithAudiences);

export declare namespace DeclarationWithoutDocsSchema {
    export interface Raw extends WithAvailability.Raw, WithAudiences.Raw {}
}
