/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ValidationSchema } from "../../validation/types/ValidationSchema.js";

export const WithValidation: core.serialization.ObjectSchema<
    serializers.WithValidation.Raw,
    FernDefinition.WithValidation
> = core.serialization.object({
    validation: ValidationSchema.optional(),
});

export declare namespace WithValidation {
    export interface Raw {
        validation?: ValidationSchema.Raw | null;
    }
}
