/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const WithName: core.serialization.ObjectSchema<serializers.WithName.Raw, FernDefinition.WithName> =
    core.serialization.object({
        name: core.serialization.string().optional(),
    });

export declare namespace WithName {
    export interface Raw {
        name?: string | null;
    }
}
