/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const WithDisplayName: core.serialization.ObjectSchema<
    serializers.WithDisplayName.Raw,
    FernDefinition.WithDisplayName
> = core.serialization.object({
    "display-name": core.serialization.string().optional(),
});

export declare namespace WithDisplayName {
    export interface Raw {
        "display-name"?: string | null;
    }
}
