/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { CursorPaginationSchema } from "./CursorPaginationSchema.js";
import { OffsetPaginationSchema } from "./OffsetPaginationSchema.js";
import { CustomPaginationSchema } from "./CustomPaginationSchema.js";

export const PaginationSchema: core.serialization.Schema<
    serializers.PaginationSchema.Raw,
    FernDefinition.PaginationSchema
> = core.serialization.undiscriminatedUnion([CursorPaginationSchema, OffsetPaginationSchema, CustomPaginationSchema]);

export declare namespace PaginationSchema {
    export type Raw = CursorPaginationSchema.Raw | OffsetPaginationSchema.Raw | CustomPaginationSchema.Raw;
}
