/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const GithubLicenseType: core.serialization.Schema<
    serializers.GithubLicenseType.Raw,
    FernDefinition.GithubLicenseType
> = core.serialization.enum_(["MIT", "Apache-2.0"]);

export declare namespace GithubLicenseType {
    export type Raw = "MIT" | "Apache-2.0";
}
