/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { GithubLicenseType } from "./GithubLicenseType.js";
import { GithubLicenseCustomSchema } from "./GithubLicenseCustomSchema.js";

export const GithubLicenseSchema: core.serialization.Schema<
    serializers.GithubLicenseSchema.Raw,
    FernDefinition.GithubLicenseSchema
> = core.serialization.undiscriminatedUnion([GithubLicenseType, GithubLicenseCustomSchema]);

export declare namespace GithubLicenseSchema {
    export type Raw = GithubLicenseType.Raw | GithubLicenseCustomSchema.Raw;
}
