/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const GithubLicenseCustomSchema: core.serialization.ObjectSchema<
    serializers.GithubLicenseCustomSchema.Raw,
    FernDefinition.GithubLicenseCustomSchema
> = core.serialization.object({
    custom: core.serialization.string(),
});

export declare namespace GithubLicenseCustomSchema {
    export interface Raw {
        custom: string;
    }
}
