/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as FernDefinition from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { ProtobufTypeSchema } from "./ProtobufTypeSchema.js";

export const EncodingSchema: core.serialization.ObjectSchema<
    serializers.fernDefinition.EncodingSchema.Raw,
    FernDefinition.fernDefinition.EncodingSchema
> = core.serialization.object({
    proto: ProtobufTypeSchema.optional(),
});

export declare namespace EncodingSchema {
    export interface Raw {
        proto?: ProtobufTypeSchema.Raw | null;
    }
}
