# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in imdb.gemspec
gemspec

group :development, :test do
  gem "rake", "~> 13.0"

  gem "minitest", "~> 5.16"
  gem "minitest-rg"

  gem "rubocop", "~> 1.21"

  gem "pry"
end
