/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const FormDataBodyEncodingStyle: core.serialization.Schema<
    serializers.FormDataBodyEncodingStyle.Raw,
    FernDefinition.FormDataBodyEncodingStyle
> = core.serialization.enum_(["json", "exploded", "form"]);

export declare namespace FormDataBodyEncodingStyle {
    export type Raw = "json" | "exploded" | "form";
}
