/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const GrpcTransport: core.serialization.ObjectSchema<
    serializers.GrpcTransport.Raw,
    FernDefinition.GrpcTransport
> = core.serialization.object({
    "service-name": core.serialization.string(),
});

export declare namespace GrpcTransport {
    export interface Raw {
        "service-name": string;
    }
}
