/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { TypeReferenceDeclarationWithEnvOverride } from "./TypeReferenceDeclarationWithEnvOverride.js";

export const HttpHeaderSchema: core.serialization.Schema<
    serializers.HttpHeaderSchema.Raw,
    FernDefinition.HttpHeaderSchema
> = TypeReferenceDeclarationWithEnvOverride;

export declare namespace HttpHeaderSchema {
    export type Raw = TypeReferenceDeclarationWithEnvOverride.Raw;
}
