/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { TypeReferenceSchema } from "../../types/types/TypeReferenceSchema.js";
import { VariableReferenceSchema } from "../../variables/types/VariableReferenceSchema.js";

export const HttpPathParameterSchema: core.serialization.Schema<
    serializers.HttpPathParameterSchema.Raw,
    FernDefinition.HttpPathParameterSchema
> = core.serialization.undiscriminatedUnion([TypeReferenceSchema, VariableReferenceSchema]);

export declare namespace HttpPathParameterSchema {
    export type Raw = TypeReferenceSchema.Raw | VariableReferenceSchema.Raw;
}
