/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { QueryParameterTypeReferenceDetailed } from "./QueryParameterTypeReferenceDetailed.js";

export const HttpQueryParameterSchema: core.serialization.Schema<
    serializers.HttpQueryParameterSchema.Raw,
    FernDefinition.HttpQueryParameterSchema
> = core.serialization.undiscriminatedUnion([core.serialization.string(), QueryParameterTypeReferenceDetailed]);

export declare namespace HttpQueryParameterSchema {
    export type Raw = string | QueryParameterTypeReferenceDetailed.Raw;
}
