/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { HttpInlineFileRequestBodyPropertySchema } from "./HttpInlineFileRequestBodyPropertySchema.js";

export const HttpInlineRequestBodyPropertySchema: core.serialization.Schema<
    serializers.HttpInlineRequestBodyPropertySchema.Raw,
    FernDefinition.HttpInlineRequestBodyPropertySchema
> = core.serialization.undiscriminatedUnion([core.serialization.string(), HttpInlineFileRequestBodyPropertySchema]);

export declare namespace HttpInlineRequestBodyPropertySchema {
    export type Raw = string | HttpInlineFileRequestBodyPropertySchema.Raw;
}
