/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { HttpReferencedRequestBodySchema } from "./HttpReferencedRequestBodySchema.js";
import { HttpInlineRequestBodySchema } from "./HttpInlineRequestBodySchema.js";

export const HttpRequestBodySchema: core.serialization.Schema<
    serializers.HttpRequestBodySchema.Raw,
    FernDefinition.HttpRequestBodySchema
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    HttpReferencedRequestBodySchema,
    HttpInlineRequestBodySchema,
]);

export declare namespace HttpRequestBodySchema {
    export type Raw = string | HttpReferencedRequestBodySchema.Raw | HttpInlineRequestBodySchema.Raw;
}
