/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { StreamFormat } from "./StreamFormat.js";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema.js";

export const HttpResponseStreamSchemaDetailed: core.serialization.ObjectSchema<
    serializers.HttpResponseStreamSchemaDetailed.Raw,
    FernDefinition.HttpResponseStreamSchemaDetailed
> = core.serialization
    .object({
        type: core.serialization.string(),
        format: StreamFormat.optional(),
        terminator: core.serialization.string().optional(),
    })
    .extend(WithDocsSchema);

export declare namespace HttpResponseStreamSchemaDetailed {
    export interface Raw extends WithDocsSchema.Raw {
        type: string;
        format?: StreamFormat.Raw | null;
        terminator?: string | null;
    }
}
