/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const HttpMethodSchema: core.serialization.Schema<
    serializers.HttpMethodSchema.Raw,
    FernDefinition.HttpMethodSchema
> = core.serialization.enum_(["GET", "POST", "PUT", "PATCH", "DELETE"]);

export declare namespace HttpMethodSchema {
    export type Raw = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
}
