/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { HttpRequestSchema } from "./HttpRequestSchema.js";

export const HttpRequest: core.serialization.Schema<serializers.HttpRequest.Raw, FernDefinition.HttpRequest> =
    core.serialization.undiscriminatedUnion([core.serialization.string(), HttpRequestSchema]);

export declare namespace HttpRequest {
    export type Raw = string | HttpRequestSchema.Raw;
}
