/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ResponseErrorWithDocsSchema } from "./ResponseErrorWithDocsSchema.js";

export const ResponseError: core.serialization.Schema<serializers.ResponseError.Raw, FernDefinition.ResponseError> =
    core.serialization.undiscriminatedUnion([core.serialization.string(), ResponseErrorWithDocsSchema]);

export declare namespace ResponseError {
    export type Raw = string | ResponseErrorWithDocsSchema.Raw;
}
