/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as FernDefinition from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { AuthSchemeReferenceSchema } from "./AuthSchemeReferenceSchema.js";

export const AnyAuthItem: core.serialization.Schema<
    serializers.fernDefinition.AnyAuthItem.Raw,
    FernDefinition.fernDefinition.AnyAuthItem
> = core.serialization.undiscriminatedUnion([core.serialization.string(), AuthSchemeReferenceSchema]);

export declare namespace AnyAuthItem {
    export type Raw = string | AuthSchemeReferenceSchema.Raw;
}
