/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as FernDefinition from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";

export const OAuthRefreshTokenRequestPropertiesSchema: core.serialization.ObjectSchema<
    serializers.fernDefinition.OAuthRefreshTokenRequestPropertiesSchema.Raw,
    FernDefinition.fernDefinition.OAuthRefreshTokenRequestPropertiesSchema
> = core.serialization.object({
    "refresh-token": core.serialization.string(),
});

export declare namespace OAuthRefreshTokenRequestPropertiesSchema {
    export interface Raw {
        "refresh-token": string;
    }
}
