/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as FernDefinition from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import { OAuthRefreshTokenRequestPropertiesSchema } from "./OAuthRefreshTokenRequestPropertiesSchema.js";
import { OAuthRefreshTokenResponsePropertiesSchema } from "./OAuthRefreshTokenResponsePropertiesSchema.js";

export const OAuthRefreshTokenEndpointSchema: core.serialization.ObjectSchema<
    serializers.fernDefinition.OAuthRefreshTokenEndpointSchema.Raw,
    FernDefinition.fernDefinition.OAuthRefreshTokenEndpointSchema
> = core.serialization.object({
    endpoint: core.serialization.string(),
    "request-properties": OAuthRefreshTokenRequestPropertiesSchema.optional(),
    "response-properties": OAuthRefreshTokenResponsePropertiesSchema.optional(),
});

export declare namespace OAuthRefreshTokenEndpointSchema {
    export interface Raw {
        endpoint: string;
        "request-properties"?: OAuthRefreshTokenRequestPropertiesSchema.Raw | null;
        "response-properties"?: OAuthRefreshTokenResponsePropertiesSchema.Raw | null;
    }
}
