/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index.js";
import * as FernDefinition from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";

export const WithDocsSchema: core.serialization.ObjectSchema<
    serializers.fernDefinition.WithDocsSchema.Raw,
    FernDefinition.fernDefinition.WithDocsSchema
> = core.serialization.object({
    docs: core.serialization.string().optional(),
});

export declare namespace WithDocsSchema {
    export interface Raw {
        docs?: string | null;
    }
}
