openapi: 3.0.1
info:
  title: query-parameters
  version: ''
paths:
  /user:
    get:
      operationId: user_getUsername
      tags:
        - User
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            nullable: true
          examples:
            Some Query Parameters:
              value: 5
        - name: id
          in: query
          required: false
          schema:
            type: string
            format: uuid
            nullable: true
          examples:
            Some Query Parameters:
              value: 4ff45b32-ca63-462d-b988-cf4eec41397a
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
            nullable: true
        - name: deadline
          in: query
          required: false
          schema:
            type: string
            format: date-time
            nullable: true
        - name: bytes
          in: query
          required: false
          schema:
            type: string
            format: byte
            nullable: true
        - name: user
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: keyValue
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: optionalString
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: nestedUser
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: optionalUser
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: excludeUser
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
              nullable: true
        - name: filter
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
              nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Some Query Parameters:
                  value:
                    name: Deep
                    tags: []
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        name:
          type: string
          example: Deep
        tags:
          type: array
          items:
            type: string
          example: []
      required:
        - name
        - tags
    NestedUser:
      title: NestedUser
      type: object
      properties:
        name:
          type: string
        user:
          $ref: '#/components/schemas/User'
      required:
        - name
        - user
  securitySchemes: {}
