/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ProtobufTypeSchema: core.serialization.ObjectSchema<
    serializers.ProtobufTypeSchema.Raw,
    FernDefinition.ProtobufTypeSchema
> = core.serialization.object({
    type: core.serialization.string(),
});

export declare namespace ProtobufTypeSchema {
    export interface Raw {
        type: string;
    }
}
