/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernSeedConfig from "../../../index.js";

export interface TestDockerConfiguration {
    image: string;
    command?: FernSeedConfig.DockerCommand;
}
