/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { UnionDiscriminant } from "./UnionDiscriminant.js";
import { ObjectExtendsSchema } from "./ObjectExtendsSchema.js";
import { TypeReferenceSchema } from "./TypeReferenceSchema.js";
import { SingleUnionTypeSchema } from "./SingleUnionTypeSchema.js";
import { BaseTypeDeclarationSchema } from "./BaseTypeDeclarationSchema.js";

export const DiscriminatedUnionSchema: core.serialization.ObjectSchema<
    serializers.DiscriminatedUnionSchema.Raw,
    FernDefinition.DiscriminatedUnionSchema
> = core.serialization
    .object({
        discriminant: UnionDiscriminant.optional(),
        extends: ObjectExtendsSchema.optional(),
        "base-properties": core.serialization.record(core.serialization.string(), TypeReferenceSchema).optional(),
        union: core.serialization.record(core.serialization.string(), SingleUnionTypeSchema),
    })
    .extend(BaseTypeDeclarationSchema);

export declare namespace DiscriminatedUnionSchema {
    export interface Raw extends BaseTypeDeclarationSchema.Raw {
        discriminant?: UnionDiscriminant.Raw | null;
        extends?: ObjectExtendsSchema.Raw | null;
        "base-properties"?: Record<string, TypeReferenceSchema.Raw> | null;
        union: Record<string, SingleUnionTypeSchema.Raw>;
    }
}
