/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { EnumValue } from "./EnumValue.js";
import { BaseTypeDeclarationSchema } from "./BaseTypeDeclarationSchema.js";

export const EnumSchema: core.serialization.ObjectSchema<serializers.EnumSchema.Raw, FernDefinition.EnumSchema> =
    core.serialization
        .object({
            default: core.serialization.string().optional(),
            enum: core.serialization.list(EnumValue),
        })
        .extend(BaseTypeDeclarationSchema);

export declare namespace EnumSchema {
    export interface Raw extends BaseTypeDeclarationSchema.Raw {
        default?: string | null;
        enum: EnumValue.Raw[];
    }
}
