/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ObjectExtendsSchema: core.serialization.Schema<
    serializers.ObjectExtendsSchema.Raw,
    FernDefinition.ObjectExtendsSchema
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace ObjectExtendsSchema {
    export type Raw = string | string[];
}
