/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const ObjectPropertyAccess: core.serialization.Schema<
    serializers.ObjectPropertyAccess.Raw,
    FernDefinition.ObjectPropertyAccess
> = core.serialization.enum_(["read-only", "write-only"]);

export declare namespace ObjectPropertyAccess {
    export type Raw = "read-only" | "write-only";
}
