/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { SingleUnionTypeKey } from "./SingleUnionTypeKey.js";
import { WithDocsSchema } from "../../commons/types/WithDocsSchema.js";
import { WithName } from "../../commons/types/WithName.js";
import { WithAvailability } from "../../commons/types/WithAvailability.js";
import { WithDisplayName } from "../../commons/types/WithDisplayName.js";

export const SingleUnionTypeDetailedSchema: core.serialization.ObjectSchema<
    serializers.SingleUnionTypeDetailedSchema.Raw,
    FernDefinition.SingleUnionTypeDetailedSchema
> = core.serialization
    .object({
        type: core.serialization.string().optional(),
        key: SingleUnionTypeKey.optional(),
    })
    .extend(WithDocsSchema)
    .extend(WithName)
    .extend(WithAvailability)
    .extend(WithDisplayName);

export declare namespace SingleUnionTypeDetailedSchema {
    export interface Raw extends WithDocsSchema.Raw, WithName.Raw, WithAvailability.Raw, WithDisplayName.Raw {
        type?: string | null;
        key?: SingleUnionTypeKey.Raw | null;
    }
}
