/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { SingleUnionTypeDetailedSchema } from "./SingleUnionTypeDetailedSchema.js";

export const SingleUnionTypeSchema: core.serialization.Schema<
    serializers.SingleUnionTypeSchema.Raw,
    FernDefinition.SingleUnionTypeSchema
> = core.serialization.undiscriminatedUnion([core.serialization.string(), SingleUnionTypeDetailedSchema]);

export declare namespace SingleUnionTypeSchema {
    export type Raw = string | SingleUnionTypeDetailedSchema.Raw;
}
