/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { ObjectSchema } from "./ObjectSchema.js";
import { EnumSchema } from "./EnumSchema.js";
import { DiscriminatedUnionSchema } from "./DiscriminatedUnionSchema.js";
import { UndiscriminatedUnionSchema } from "./UndiscriminatedUnionSchema.js";
import { AliasSchema } from "./AliasSchema.js";

export const TypeDeclarationSchema: core.serialization.Schema<
    serializers.TypeDeclarationSchema.Raw,
    FernDefinition.TypeDeclarationSchema
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    ObjectSchema,
    EnumSchema,
    DiscriminatedUnionSchema,
    UndiscriminatedUnionSchema,
    AliasSchema,
]);

export declare namespace TypeDeclarationSchema {
    export type Raw =
        | string
        | ObjectSchema.Raw
        | EnumSchema.Raw
        | DiscriminatedUnionSchema.Raw
        | UndiscriminatedUnionSchema.Raw
        | AliasSchema.Raw;
}
