/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as FernDefinition from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { SingleUndiscriminatedUnionTypeSchema } from "./SingleUndiscriminatedUnionTypeSchema.js";
import { BaseTypeDeclarationSchema } from "./BaseTypeDeclarationSchema.js";

export const UndiscriminatedUnionSchema: core.serialization.ObjectSchema<
    serializers.UndiscriminatedUnionSchema.Raw,
    FernDefinition.UndiscriminatedUnionSchema
> = core.serialization
    .object({
        discriminated: core.serialization.booleanLiteral(false),
        union: core.serialization.list(SingleUndiscriminatedUnionTypeSchema),
    })
    .extend(BaseTypeDeclarationSchema);

export declare namespace UndiscriminatedUnionSchema {
    export interface Raw extends BaseTypeDeclarationSchema.Raw {
        discriminated: false;
        union: SingleUndiscriminatedUnionTypeSchema.Raw[];
    }
}
