name: ci

on:
  push:
    paths:
      - "packages/**"
      # IR snapshot tests run on test definitions
      - "test-definitions/**"
      # Add any generators that are written in TypeScript
      - "generators/openapi/**"
      - "generators/postman/**"
      - "generators/ruby/**"
      - "generators/typescript/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      # IR snapshot tests run on test definitions
      - "test-definitions/**"
      # Add any generators that are written in TypeScript
      - "generators/openapi/**"
      - "generators/postman/**"
      - "generators/ruby/**"
      - "generators/typescript/**"
    branches:
      - main

# Cancel previous workflows on previous push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Lint Monorepo
        run: pnpm lint:monorepo

      - name: Check dependencies
        run: pnpm depcheck

      - name: Lint
        run: pnpm lint:style

      - name: generate (dev) JSON Schema
        run: pnpm generate-json-schema:dev

      - name: Format
        run: pnpm format:check

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  compile:
    runs-on: CLI
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: compile
        run: pnpm compile

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: lint:eslint
        run: pnpm lint:eslint

  test:
    runs-on: Test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Run tests
        run: pnpm test --maxWorkers 15 --ci --silent

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  ete-tests:
    runs-on: CLI
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Run ETE tests
        env:
          FERN_ORG_TOKEN_DEV: ${{ secrets.FERN_ORG_TOKEN_DEV }}
        run: |
          FERN_TOKEN=${{ secrets.FERN_ORG_TOKEN_DEV }} pnpm test:ete

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  live-test-dev:
    environment: Fern Dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Check API definition is valid
        env:
          FORCE_COLOR: "2"
          FERN_ORG_TOKEN_DEV: ${{ secrets.FERN_ORG_TOKEN_DEV }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        run: |
          pnpm --filter=@fern-api/cli dist:cli:dev
          cli_path="$(pnpm --filter=@fern-api/cli bin fern:dev)"
          ./scripts/live-test.sh "$cli_path" "$FERN_ORG_TOKEN_DEV"
