on:
  push:
    branches:
      - dsinghvi/ruby-tweaks

jobs:
  ruby-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Install
        run: yarn install

      - name: Build CLI
        working-directory: ./generators/ruby/sdk
        run: yarn dist:cli

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./generators/ruby/sdk/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=min
          push: true
          labels: version=0.9.0-rc0
          tags: fernapi/fern-ruby-sdk:0.9.0-rc0
