name: Python Generator

on:
  pull_request:
    paths:
      - "generators/python/**"
    branches:
      - main
  workflow_call:

jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5

      - name: Install Dependencies
        working-directory: ./generators/python
        run: poetry install

      - name: Type check
        working-directory: ./generators/python
        run: poetry run mypy --show-traceback

      - name: pre-commit
        working-directory: ./generators/python
        run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5

      - name: Update models for testing
        working-directory: ./generators/python
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          npm install -g fern-api

          docker build -f ./pydantic/Dockerfile -t ferntest/fern-pydantic-model:0.0.0 .
          cd tests/utils/example_models
          fern generate --group dummy_types --local || true

          cd ../typeddict_models
          fern generate --group dummy_td_types --local || true

          cd ../union_utils
          fern generate --group dummy_union_types --local || true

          cd ../unaliased_models
          fern generate --group dummy_unaliased_types --local || true

      - name: Unit Test
        working-directory: ./generators/python
        run: |
          poetry lock
          poetry install
          poetry run pytest -sv
