name: seed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

# Cancel previous workflows on previous push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: macos-14
    outputs:
      seed: ${{ steps.filter.outputs.seed }}
      ruby: ${{ steps.filter.outputs.ruby }}
      openapi: ${{ steps.filter.outputs.openapi }}
      python: ${{ steps.filter.outputs.python }}
      postman: ${{ steps.filter.outputs.postman }}
      java: ${{ steps.filter.outputs.java }}
      typescript: ${{ steps.filter.outputs.typescript }}
      go: ${{ steps.filter.outputs.go }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            seed: 
              - '.github/workflows/seed.yml'
              - 'packages/seed/**'
              - 'test-definitions/**'
            ruby: 'generators/ruby/**'
            openapi: 'generators/openapi/**'
            python: 'generators/python/**'
            postman: 'generators/postman/**'
            java: 'generators/java/**'
            typescript: 'generators/typescript/**'
            go: 'generators/go/**'

  ruby-model:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.ruby == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Seed
        env:
          FORCE_COLOR: "2"
        run: npm install -g @fern-api/seed-cli

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        run: |
          yarn seed:local test --workspace ruby-model

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  ruby-sdk:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.ruby == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Seed
        run: npm install -g @fern-api/seed-cli

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace ruby-sdk

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  pydantic-model:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        working-directory: ./generators/python
        run: poetry install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace pydantic

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  python-sdk:
    runs-on: macos-14-xlarge
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        working-directory: ./generators/python
        run: poetry install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace python-sdk --parallel 10

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  fastapi:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        working-directory: ./generators/python
        run: poetry install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace fastapi

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  openapi:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.openapi == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace openapi

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  postman:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.postman == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace postman

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  java-sdk:
    runs-on: macos-14-xlarge
    needs: changes
    if: ${{ needs.changes.outputs.java == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace java-sdk --parallel 10

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  java-model:
    runs-on: macos-14-xlarge
    needs: changes
    if: ${{ needs.changes.outputs.java == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace java-model --parallel 10

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  java-spring:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.java == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace java-spring

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  typescript-sdk:
    runs-on: macos-14-xlarge
    needs: changes
    if: ${{ needs.changes.outputs.typescript == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace ts-sdk

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  typescript-express:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.typescript == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace ts-express  --parallel 1

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  go-fiber:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace go-fiber --parallel 16

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  go-model:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace go-model --parallel 16

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code

  go-sdk:
    runs-on: macos-14
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' ||  needs.changes.outputs.seed == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Docker
        run: brew install docker

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Yarn Install
        run: yarn install

      - name: Seed Test
        env:
          FORCE_COLOR: "2"
        run: |
          yarn seed:local test --workspace go-sdk --parallel 16

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff --exit-code
