name: run-vale

on:
  pull_request

jobs:
  run:
    name: vale
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: fern/pages/