name: Check Docs with Vale

on: 
  pull_request:
    paths:
      - "fern/pages/**"

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: fern/pages/